param:

    chunksize:              5_000_000
    folder:                 'data'

    connection_config_file: config.yaml
    config_file_section:    local

files:

    movies:

        name_file:          title.basics.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['tconst']
        column_types:

            tconst:             VARCHAR 10
            titleType:          VARCHAR 15
            primaryTitle:       VARCHAR 500
            originalTitle:      VARCHAR 500
            isAdult:            BOOLEAN
            startYear:          SMALLINT
            endYear:            SMALLINT
            runtimeMinutes:     INTEGER
            genres:             VARCHAR 100

    persons:

        name_file:          name.basics.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['nconst']
        column_types:

            nconst:             VARCHAR 10
            primaryName:        VARCHAR 300
            birthYear:          SMALLINT
            deathYear:          SMALLINT
            primaryProfession:  VARCHAR 300

    knownfor:

        name_file:          name.basics.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['nconst', 'tconst']
        foreign_keys:

            nconst:             persons(nconst)
            tconst:             movies(tconst)

        explode_on :        knownForTitles
        explode_new_name :  tconst
        column_types:

            nconst:             VARCHAR 10
            tconst:             VARCHAR 10

    titles:

        name_file:          title.akas.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['titleId', 'ordering']
        foreign_keys:

            titleId:             movies(tconst)

        column_types:

            titleId:            VARCHAR 10
            ordering:           SMALLINT
            title:              VARCHAR 1000
            region:             VARCHAR 5
            language:           VARCHAR 5
            types:              VARCHAR 40
            attributes:         VARCHAR 255
            isOriginalTitle:    BOOLEAN

    directors:

        name_file:          title.crew.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['nconst', 'tconst']

        foreign_keys:

            nconst:             persons(nconst)
            tconst:             movies(tconst)

        explode_on :        directors
        explode_new_name :  nconst
        column_types:

            nconst:             VARCHAR 10
            tconst:             VARCHAR 10

    writers:

        name_file:          title.crew.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['nconst', 'tconst']
        foreign_keys:

            nconst:             persons(nconst)
            tconst:             movies(tconst)

        explode_on :        writers
        explode_new_name :  nconst
        column_types:

            nconst:             VARCHAR 10
            tconst:             VARCHAR 10

    episodes:

        name_file:          title.episode.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['tconst']
        foreign_keys:

            tconst:             movies(tconst)
            parentTconst:       movies(tconst)

        column_types:

            tconst:             VARCHAR 10
            parentTconst:       VARCHAR 10
            seasonNumber:       SMALLINT
            episodeNumber:      INTEGER

    principals:

        name_file:          title.principals.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['tconst', 'ordering']
        foreign_keys:

            nconst:             persons(nconst)
            tconst:             movies(tconst)

        column_types:

            tconst:             VARCHAR 10
            ordering:           SMALLINT
            nconst:             VARCHAR 10
            category:           VARCHAR 20
            job:                VARCHAR 300
            characters:         VARCHAR 1400

    ratings:

        name_file:          title.ratings.tsv.gz
        na_values:          ['\N', 'N']
        primary_keys:       ['tconst']
        foreign_keys:

            tconst:             movies(tconst)

        column_types:

            tconst:             VARCHAR 10
            averageRating:      FLOAT
            numVotes:           INTEGER